version: '3'

services:
   nifs-retrieve-example:
     image: koyom/nifs-retrieve:latest
     restart: always
     ports:
        - "127.0.0.1:8888:8888"
     container_name: nifs-retrieve-example
     command: ["jupyter", "notebook", "--no-browser", "--port=8888", "--ip=0.0.0.0",
               "--allow-root", "--NotebookApp.token=''"]
     volumes:
       - ${PWD}/docs/source/examples:/home/examples
